workflows:
  android-apk-build:
    name: Compilar APK Calculadora
    max_build_duration: 15
    instance_type: mac_mini_m2
    triggering:
      events:
        - push
    scripts:
      - name: Compilar APK
        script: |
          REAL_GRADLEW=$(find . -name "gradlew" | head -n 1)
          
          if [ -n "$REAL_GRADLEW" ]; then
            cd "$(dirname "$REAL_GRADLEW")"
            chmod +x gradlew
            ./gradlew assemble --quiet
          else
            REAL_DIR=$(dirname $(find . -name "build.gradle*" | head -n 1))
            cd "$REAL_DIR"
            gradle assemble --quiet
          fi
    artifacts:
      - "**/build/outputs/apk/**/*.apk"





