name: Compilar APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar codigo del repo
      uses: actions/checkout@v4

    - name: Configurar Java JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Encontrar y dar permisos a Gradle
      run: |
        GRADLEW_PATH=$(find . -name gradlew)
        echo "GRADLEW_DIR=$(dirname $GRADLEW_PATH)" >> $GITHUB_ENV
        echo "GRADLEW_EXEC=$GRADLEW_PATH" >> $GITHUB_ENV
        chmod +x $GRADLEW_PATH

    - name: Compilar APK de depuracion
      run: |
        cd ${{ env.GRADLEW_DIR }}
        ./gradlew assembleDebug

    - name: Subir APK finalizado
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: "**/build/outputs/apk/debug/*.apk"
